### ISSUE TITLE
setup.py version is 0.4.0 while pypi is 0.5.0

### ISSUE THREAD

**Issue by mroutis** [carletes/mock-ssh-server#10]
Hello! I'm wondering if you can release a 0.5.1 version including these changes: https://github.com/carletes/mock-ssh-server/pull/9

Also, I noticed that the version specified on the `setup.py` don't match the one in https://pypi.org/project/mock-ssh-server/#history

**Comment by carletes** [comment]
Thanks, @mroutis! I just tagged the current head of the master branch as 0.6.0, and pushed it to PyPI (https://pypi.org/project/mock-ssh-server/)

**Comment by carletes** [comment]
@mroutis: I've given you access as collaborator to this Github project. If you need to make changes to this project in the future:

1. Open a PR as usual (with tests, like what you did for `lstat()` and `symlink()`)
2. If you don't hear from me or from @mvdbeek in a couple of days, merge it into master.

If you have a PyPI handle, please give it to me, so that I may add you to the list of maintainers in https://pypi.org/project/mock-ssh-server/. That way you will also be able to push your changes to PyPI, in case @mvdbeek or I are not around.

**Comment by mroutis** [comment]
Thanks a lot, @carletes, appreciate the trust!

This is my profile at PyPi https://pypi.org/user/mroutis/
